'use client';

import { FormEvent, useMemo, useState } from 'react';

type Service = { id:string; no:string; title:string; short:string; desc:string; tags:string; question:string; options:string[] };
const services: Service[] = [
  {id:'management',no:'01',title:'Property management',short:'Property management',desc:'Turn your property into a well-run guest experience.',tags:'Operations · Bookings · Guest care',question:'What do you need the most help with?',options:['Full property management','Marketing & bookings','Guest handling & operations','Staff & maintenance']},
  {id:'build',no:'02',title:'Airbnb planning & build',short:'Airbnb planning & build',desc:'Plan, build, set up, and launch with practical guidance.',tags:'Concept · Construction · Launch',question:'What stage are you in?',options:['Idea / planning','Already have a lot','Design or construction','Almost ready to launch']},
  {id:'arbitrage',no:'03',title:'Rental arbitrage',short:'Rental arbitrage',desc:'Start an Airbnb business without owning a property.',tags:'Capital · Location · Strategy',question:'What starting capital is available?',options:['Below ₱100k','₱100k–₱200k','₱200k–₱300k','₱300k–₱500k','₱500k+']},
  {id:'investment',no:'04',title:'Investment & partnership',short:'Investment & partnership',desc:'Explore project partnerships built around real operations.',tags:'₱1M+ · Passive income · Projects',question:'What capital is available?',options:['₱1M','₱2M','₱3M','₱4M+']},
  {id:'systems',no:'05',title:'Custom systems & web apps',short:'Custom systems & web apps',desc:'Shape a system around how your business actually works.',tags:'CRM · Automation · Portals',question:'How do you manage the business today?',options:['Mostly manual','Google Sheets','Messenger / Chat','Multiple apps','Existing software','No system yet']},
];
const leads = [
  {initials:'AM',name:'Angela Mendoza',service:'Property management',time:'Sep 8 · 7:30 PM',budget:'₱300k–₱500k',place:'Tagaytay',priority:'High priority',status:'Pending'},
  {initials:'JL',name:'Jerome Lim',service:'Airbnb planning & build',time:'Sep 8 · 8:30 PM',budget:'₱3M–₱5M',place:'Batangas',priority:'High priority',status:'Pending'},
  {initials:'RC',name:'Rina Cruz',service:'Custom systems & web apps',time:'Sep 9 · 7:00 PM',budget:'₱100k–₱300k',place:'Manila',priority:'Follow up',status:'Approved'},
  {initials:'MD',name:'Marco Diaz',service:'Rental arbitrage',time:'Sep 9 · 9:30 PM',budget:'₱100k–₱200k',place:'Cebu',priority:'Nurture',status:'Pending'},
];

export default function Home(){
 const [view,setView]=useState<'site'|'admin'>('site');
 const [selected,setSelected]=useState<Service|null>(null);
 const [step,setStep]=useState(1); const [sent,setSent]=useState(false);
 const [slot,setSlot]=useState('7:30 PM'); const [day,setDay]=useState(8);
 const service=selected||services[0];
 const dates=useMemo(()=>[7,8,9,10,11],[]);
 function openForm(s?:Service){setSelected(s||services[0]);setStep(1);setSent(false)}
 function submit(e:FormEvent){e.preventDefault(); if(step<3)setStep(step+1);else setSent(true)}
 if(view==='admin') return <Admin onExit={()=>setView('site')}/>;
 return <main>
  <nav className="nav shell"><a className="brand" href="#top"><span>H</span> Hostly <b>Solutions</b></a><div className="navlinks"><a href="#story">Our story</a><a href="#services">Ways we help</a><button className="linkbutton" onClick={()=>setView('admin')}>Admin</button><button onClick={()=>openForm()}>Request a free call</button></div></nav>
  <section className="hero shell" id="top"><div className="eyebrow"><i/>Real experience, shared practically</div><h1>We started by renting.<br/>Then we built. <em>Then we scaled.</em></h1><p>Practical assistance for property owners, Airbnb builders, operators, investors, and growing businesses—from a team that has done the work firsthand.</p><div className="actions"><button className="primary" onClick={()=>document.querySelector('#services')?.scrollIntoView()}>Find the right assistance <span>↗</span></button><a className="secondary" href="#story">See our journey <span>↓</span></a></div><div className="trust"><div><strong>20+</strong><span>team members</span></div><div><strong>5</strong><span>ways we can assist</span></div><div><strong>30 min</strong><span>free consultation</span></div></div></section>
  <section className="story" id="story"><div className="shell storygrid"><div><span className="sectionno">01 / OUR STORY</span><h2>We only share what we’ve already lived.</h2></div><div><p>Hostly grew from a one-person rental arbitrage operation into a hands-on hospitality team—building villas, managing multiple properties, and creating the systems behind every booking and guest stay.</p><div className="journey"><span>Rented</span><i>→</i><span>Built</span><i>→</i><span>Scaled</span><i>→</i><span>Systemized</span></div></div></div></section>
  <section className="services shell" id="services"><div className="sectionhead"><div><span className="sectionno">02 / WAYS WE HELP</span><h2>Where are you in your journey?</h2></div><p>Choose the path closest to your situation. We’ll ask a few focused questions to understand the fit.</p></div><div className="servicegrid">{services.map(s=><button className="service" key={s.id} onClick={()=>openForm(s)}><span className="serviceNo">{s.no}</span><div><h3>{s.title}</h3><p>{s.desc}</p><small>{s.tags}</small></div><span className="arrow">↗</span></button>)}</div></section>
  <section className="consult"><div className="shell consultInner"><div><span className="sectionno">A CLEAR NEXT STEP</span><h2>Not sure where to begin?</h2><p>Tell us where you are today. We’ll review the details before confirming a focused, free 30-minute conversation.</p></div><button className="lightCta" onClick={()=>openForm()}>Request a free consultation <span>↗</span></button></div></section>
  <footer className="shell"><a className="brand" href="#top"><span>H</span> Hostly <b>Solutions</b></a><p>Built from experience. Shared with purpose.</p><small>© 2026 Hostly Solutions</small></footer>
  {selected&&<div className="modalWrap" role="dialog" aria-modal="true"><div className="modal"><button className="close" aria-label="Close" onClick={()=>setSelected(null)}>×</button>{sent?<Success service={service.short} day={day} slot={slot} onClose={()=>setSelected(null)}/>:<><div className="progress"><span>STEP {step} OF 3</span><i><b style={{width:`${step*33.34}%`}}/></i></div><form onSubmit={submit}>{step===1&&<><span className="formKicker">YOU SELECTED</span><h2>{service.title}</h2><p>Let’s understand your situation. It takes less than two minutes.</p><div className="formGrid"><label>Full name<input required placeholder="Your full name"/></label><label>Email address<input required type="email" placeholder="you@email.com"/></label><label className="wide">Mobile / Messenger<input required placeholder="e.g. 0917 123 4567"/></label></div></>}{step===2&&<><span className="formKicker">A FEW DETAILS</span><h2>Help us understand the fit.</h2><label>{service.question}<select required defaultValue=""><option value="" disabled>Select an answer</option>{service.options.map(o=><option key={o}>{o}</option>)}</select></label><label>Preferred location<input required placeholder="City or province"/></label><label>When would you like to start?<select defaultValue="Within 30 days"><option>ASAP</option><option>Within 30 days</option><option>Within 1–3 months</option><option>Just exploring</option></select></label></>}{step===3&&<><span className="formKicker">PREFERRED SCHEDULE</span><h2>Choose a time that works.</h2><p>Your request stays pending until our team reviews and confirms it.</p><div className="dateRow">{dates.map((d,i)=><button type="button" key={d} className={day===d?'date active':'date'} onClick={()=>setDay(d)}><span>{['MON','TUE','WED','THU','FRI'][i]}</span><strong>{d}</strong></button>)}</div><div className="slots">{['7:00 PM','7:30 PM','8:00 PM','8:30 PM','9:00 PM','9:30 PM'].map(t=><button type="button" key={t} className={slot===t?'active':''} onClick={()=>setSlot(t)}>{t}</button>)}</div><div className="notice">◷ &nbsp; Free 30-minute consultation · Asia/Manila time</div></>}<div className="formActions">{step>1&&<button type="button" className="back" onClick={()=>setStep(step-1)}>← Back</button>}<button className="continue" type="submit">{step===3?'Send consultation request':'Continue'} <span>→</span></button></div></form></>}</div></div>}
 </main>
}

function Success({service,day,slot,onClose}:{service:string;day:number;slot:string;onClose:()=>void}){return <div className="success"><div className="check">✓</div><span className="formKicker">REQUEST RECEIVED</span><h2>Thanks—we’ll review the fit.</h2><p>Your {service} consultation request is pending approval. We’ll email you after our team reviews it.</p><div className="summary"><div><span>Preferred schedule</span><strong>September {day}, 2026 · {slot}</strong></div><div><span>Duration</span><strong>Approximately 30 minutes</strong></div><div><span>Status</span><strong className="pendingDot">● Pending approval</strong></div></div><button className="continue" onClick={onClose}>Return to Hostly</button></div>}

function Admin({onExit}:{onExit:()=>void}){const [filter,setFilter]=useState('All consultations');return <div className="admin"><aside><a className="brand"><span>H</span> Hostly <b>Solutions</b></a><div className="adminLabel">WORKSPACE</div><nav><button className="active">▣ Consultations <b>4</b></button><button>♙ Clients / leads</button><button>✉ Send offer email</button></nav><div className="adminLabel">MANAGE</div><nav><button>◷ Availability</button><button>◇ Opportunities</button><button>⚙ Settings</button></nav><div className="adminUser"><i>MA</i><div><strong>Maria Admin</strong><span>Appointment setter</span></div></div></aside><section className="adminMain"><header><div><span>MONDAY, SEPTEMBER 7</span><h1>Consultations</h1></div><div><button className="iconBtn">⌕</button><button className="iconBtn">♢</button><button className="newBtn">＋ Add lead</button><button className="exitBtn" onClick={onExit}>View site ↗</button></div></header><div className="metrics"><article><span>Pending review</span><strong>4</strong><small>Needs your attention</small></article><article><span>Approved this week</span><strong>7</strong><small className="good">↑ 2 from last week</small></article><article><span>High priority</span><strong>6</strong><small>Across all leads</small></article><article><span>Upcoming today</span><strong>3</strong><small>Next at 7:30 PM</small></article></div><div className="tableCard"><div className="tableTop"><div className="tabs">{['All consultations','Pending','Approved','Rescheduled'].map(x=><button key={x} className={filter===x?'active':''} onClick={()=>setFilter(x)}>{x}{x==='Pending'&&<b>4</b>}</button>)}</div><button className="filterBtn">☷ Filter</button></div><div className="leadTable"><div className="tr th"><span>CLIENT</span><span>ASSISTANCE</span><span>REQUESTED TIME</span><span>QUALIFICATION</span><span>STATUS</span><span></span></div>{leads.filter(x=>filter==='All consultations'||x.status===filter).map(l=><div className="tr" key={l.name}><span className="person"><i>{l.initials}</i><div><strong>{l.name}</strong><small>{l.place} · {l.budget}</small></div></span><span>{l.service}</span><span><strong>{l.time}</strong><small>30 minutes</small></span><span><b className={'pill '+l.priority.toLowerCase().replace(' ','')}>{l.priority}</b></span><span><b className={'status '+l.status.toLowerCase()}>● {l.status}</b></span><button className="dots">•••</button></div>)}</div></div></section></div>}
