'use client';

import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import type { Session } from '@supabase/supabase-js';
import { createSupabaseBrowser } from '../lib/supabase/browser';

const ADMIN_EMAIL = 'marjunlopez23300@gmail.com';
const serviceLabels: Record<string,string> = {
  PROPERTY_MANAGEMENT:'Property management', AIRBNB_PLANNING_BUILD:'Airbnb planning & build',
  RENTAL_ARBITRAGE:'Rental arbitrage', INVESTMENT_PARTNERSHIP:'Investment & partnership',
  CUSTOM_SYSTEM_WEB_APP:'Custom systems & web apps',
};
const statusLabels: Record<string,string> = {
  PENDING_APPROVAL:'Pending', APPROVED:'Approved', RESCHEDULED:'Rescheduled', DECLINED:'Declined',
  COMPLETED:'Completed', NO_SHOW:'No show', CANCELLED:'Cancelled',
};
const crmLabels: Record<string,string> = {
  NEW_LEAD:'New lead', QUALIFIED:'Qualified', FOLLOW_UP:'Follow up', CONSULTATION_REQUESTED:'Consultation requested',
  PENDING_APPROVAL:'Pending approval', CONSULTATION_APPROVED:'Consultation approved', RESCHEDULED:'Rescheduled',
  CONSULTATION_COMPLETED:'Consultation completed', PROPOSAL_DISCUSSION:'Proposal discussion',
  INTERESTED_DEAL:'Interested deal', CLOSED_WON:'Closed won', CLOSED_LOST:'Closed lost', NURTURE:'Nurture', DO_NOT_PURSUE:'Do not pursue',
};

type Lead = { id:string; full_name:string; email:string; mobile:string; service_type:string; qualification_status:string; crm_status:string; preferred_location:string|null; budget_range:string|null; start_timeframe:string|null; last_activity_at:string };
type Consultation = { id:string; requested_datetime:string; approved_datetime:string|null; status:string; meeting_url:string|null; calendar_event_id:string|null; admin_notes:string|null; created_at:string; leads:Lead };
type Draft = { status:string; requestedAt:string; adminNotes:string };
type Section = 'consultations'|'crm';

function localInput(iso:string){const d=new Date(iso);const p=(n:number)=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`}
function initials(name:string){return name.split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase()}
function calendarUrl(item:Consultation){const start=new Date(item.approved_datetime||item.requested_datetime);const end=new Date(start.getTime()+30*60000);const stamp=(d:Date)=>d.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');const details=`Hostly consultation with ${item.leads.full_name}\nService: ${serviceLabels[item.leads.service_type]}\nPhone: ${item.leads.mobile}\nEmail: ${item.leads.email}`;const q=new URLSearchParams({action:'TEMPLATE',text:`Hostly consultation — ${item.leads.full_name}`,dates:`${stamp(start)}/${stamp(end)}`,details,add:item.leads.email});return `https://calendar.google.com/calendar/render?${q}`}

export default function Admin({onExit}:{onExit:()=>void}){
  const supabase=useMemo(()=>createSupabaseBrowser(),[]);
  const [session,setSession]=useState<Session|null>(null);const [loading,setLoading]=useState(true);const [sending,setSending]=useState(false);
  const [password,setPassword]=useState('');const [section,setSection]=useState<Section>('consultations');
  const [items,setItems]=useState<Consultation[]>([]);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [filter,setFilter]=useState('ALL');
  const [search,setSearch]=useState('');const [crmFilter,setCrmFilter]=useState('ALL');
  const [editing,setEditing]=useState<Consultation|null>(null);const [draft,setDraft]=useState<Draft>({status:'PENDING_APPROVAL',requestedAt:'',adminNotes:''});
  const [creating,setCreating]=useState(false);const [newLead,setNewLead]=useState({fullName:'',email:'',mobile:'',location:'',serviceType:'PROPERTY_MANAGEMENT',requestedAt:''});

  const api=useCallback(async(path:string,options?:RequestInit)=>{const token=session?.access_token;if(!token)throw new Error('Please sign in again.');const response=await fetch(path,{...options,headers:{'content-type':'application/json',authorization:`Bearer ${token}`,...options?.headers}});const result=await response.json() as {error?:string;consultations?:Consultation[]};if(!response.ok)throw new Error(result.error||'Request failed.');return result},[session]);
  const load=useCallback(async()=>{if(!session)return;setLoading(true);setError('');try{const result=await api('/api/admin/consultations');setItems(result.consultations||[])}catch(e){setError(e instanceof Error?e.message:'Unable to load consultations.')}finally{setLoading(false)}},[api,session]);
  useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)});const {data}=supabase.auth.onAuthStateChange((_event,next)=>setSession(next));return()=>data.subscription.unsubscribe()},[supabase]);
  useEffect(()=>{if(session)queueMicrotask(()=>void load())},[session,load]);

  async function signIn(e:FormEvent){e.preventDefault();setSending(true);setError('');const {error:authError}=await supabase.auth.signInWithPassword({email:ADMIN_EMAIL,password});if(authError)setError('Invalid email or password.');setSending(false)}
  async function save(e:FormEvent){e.preventDefault();if(!editing)return;setError('');try{await api(`/api/admin/consultations/${editing.id}`,{method:'PATCH',body:JSON.stringify({...draft,currentRequestedAt:editing.requested_datetime})});setEditing(null);setNotice('Consultation updated.');await load()}catch(e){setError(e instanceof Error?e.message:'Unable to update.') }}
  async function remove(item:Consultation){if(!window.confirm(`Delete ${item.leads.full_name}'s consultation and lead record?`))return;setError('');try{await api(`/api/admin/consultations/${item.id}`,{method:'DELETE'});setNotice('Consultation deleted.');await load()}catch(e){setError(e instanceof Error?e.message:'Unable to delete.') }}
  async function create(e:FormEvent){e.preventDefault();setError('');try{await api('/api/admin/consultations',{method:'POST',body:JSON.stringify({...newLead,requestedAt:new Date(newLead.requestedAt).toISOString()})});setCreating(false);setNewLead({fullName:'',email:'',mobile:'',location:'',serviceType:'PROPERTY_MANAGEMENT',requestedAt:''});setNotice('Lead created.');await load()}catch(e){setError(e instanceof Error?e.message:'Unable to create.') }}
  async function updateStage(lead:Lead,crmStatus:string){setError('');try{await api(`/api/admin/leads/${lead.id}`,{method:'PATCH',body:JSON.stringify({crmStatus})});setItems(current=>current.map(item=>item.leads.id===lead.id?{...item,leads:{...item.leads,crm_status:crmStatus,last_activity_at:new Date().toISOString()}}:item));setNotice(`${lead.full_name} moved to ${crmLabels[crmStatus]}.`)}catch(e){setError(e instanceof Error?e.message:'Unable to update CRM stage.') }}
  function edit(item:Consultation){setEditing(item);setDraft({status:item.status,requestedAt:localInput(item.requested_datetime),adminNotes:item.admin_notes||''})}

  if(!session)return <div className="adminLogin"><button className="exitBtn" onClick={onExit}>← Back to site</button><form className="loginCard" onSubmit={signIn}><div className="loginMark">H</div><span className="formKicker">HOSTLY ADMIN</span><h1>Secure workspace access</h1><p>Sign in with the administrator account configured in Supabase Auth.</p><label>Admin email<input type="email" value={ADMIN_EMAIL} disabled/></label><label>Password<input required type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Enter your password"/></label>{error&&<p className="formError">{error}</p>}<button className="continue" type="submit" disabled={sending}>{sending?'Signing in…':'Sign in to admin'}</button></form></div>;

  const leads=Array.from(new Map(items.map(item=>[item.leads.id,item.leads])).values());
  const shown=items.filter(x=>filter==='ALL'||x.status===filter);
  const visibleLeads=leads.filter(lead=>{const q=search.trim().toLowerCase();const matches=!q||[lead.full_name,lead.email,lead.mobile,lead.preferred_location||'',serviceLabels[lead.service_type]||''].some(v=>v.toLowerCase().includes(q));return matches&&(crmFilter==='ALL'||lead.crm_status===crmFilter)});
  const pending=items.filter(x=>x.status==='PENDING_APPROVAL').length;

  return <div className="admin"><aside><div className="adminBrand">HOSTLY<small>ADMIN WORKSPACE</small></div><div className="adminLabel">WORKSPACE</div><nav><button className={section==='consultations'?'active':''} onClick={()=>setSection('consultations')}>▣ Consultations <b>{pending}</b></button><button className={section==='crm'?'active':''} onClick={()=>setSection('crm')}>♙ CRM / Leads <b>{leads.length}</b></button></nav><div className="adminUser"><i>ML</i><div><strong>Marjun Lopez</strong><span>{ADMIN_EMAIL}</span></div></div></aside><section className="adminMain"><header><div><span>LIVE SUPABASE DATA</span><h1>{section==='crm'?'CRM / Leads':'Consultations'}</h1></div><div><button className="iconBtn" onClick={()=>void load()}>↻ Refresh</button><button className="newBtn" onClick={()=>setCreating(true)}>＋ Add lead</button><button className="exitBtn" onClick={onExit}>View site ↗</button><button className="exitBtn" onClick={()=>supabase.auth.signOut()}>Sign out</button></div></header>{error&&<p className="formError">{error}</p>}{notice&&<p className="formNotice">{notice}</p>}
  {section==='consultations'?<ConsultationsView items={items} shown={shown} loading={loading} filter={filter} setFilter={setFilter} edit={edit} remove={remove}/>:<CrmView leads={leads} visibleLeads={visibleLeads} loading={loading} search={search} setSearch={setSearch} crmFilter={crmFilter} setCrmFilter={setCrmFilter} updateStage={updateStage}/>}
  </section>{(editing||creating)&&<EditorModal editing={editing} draft={draft} setDraft={setDraft} newLead={newLead} setNewLead={setNewLead} save={save} create={create} close={()=>{setEditing(null);setCreating(false)}}/>}</div>
}

function ConsultationsView({items,shown,loading,filter,setFilter,edit,remove}:{items:Consultation[];shown:Consultation[];loading:boolean;filter:string;setFilter:(value:string)=>void;edit:(item:Consultation)=>void;remove:(item:Consultation)=>void}){
  const pending=items.filter(x=>x.status==='PENDING_APPROVAL').length;const approved=items.filter(x=>x.status==='APPROVED').length;
  return <><div className="metrics"><article><span>Total requests</span><strong>{items.length}</strong><small>From Supabase</small></article><article><span>Pending review</span><strong>{pending}</strong><small>Needs attention</small></article><article><span>Approved</span><strong>{approved}</strong><small>Ready for calendar</small></article><article><span>Completed</span><strong>{items.filter(x=>x.status==='COMPLETED').length}</strong><small>Finished calls</small></article></div><div className="tableCard"><div className="tableTop"><div className="tabs">{[['ALL','All'],['PENDING_APPROVAL','Pending'],['APPROVED','Approved'],['COMPLETED','Completed']].map(([key,label])=><button key={key} className={filter===key?'active':''} onClick={()=>setFilter(key)}>{label}</button>)}</div></div>{loading?<p className="emptyState">Loading consultations…</p>:shown.length===0?<p className="emptyState">No consultations in this view.</p>:<div className="leadTable"><div className="tr th"><span>CLIENT</span><span>ASSISTANCE</span><span>REQUESTED TIME</span><span>QUALIFICATION</span><span>STATUS</span><span></span></div>{shown.map(item=><div className="tr" key={item.id}><span className="person"><i>{initials(item.leads.full_name)}</i><div><strong>{item.leads.full_name}</strong><small>{item.leads.email}<br/>{item.leads.preferred_location||'No location'}</small></div></span><span>{serviceLabels[item.leads.service_type]||item.leads.service_type}</span><span><strong>{new Date(item.requested_datetime).toLocaleString('en-PH',{dateStyle:'medium',timeStyle:'short'})}</strong><small>30 minutes</small></span><span><b className="pill followup">{item.leads.qualification_status.replaceAll('_',' ')}</b></span><span><b className={`status ${item.status==='APPROVED'?'approved':'pending'}`}>● {statusLabels[item.status]||item.status}</b></span><span className="rowActions"><button onClick={()=>edit(item)}>Edit</button>{item.meeting_url?<a href={item.meeting_url} target="_blank" rel="noreferrer">Booking link</a>:item.status==='APPROVED'&&<a href={calendarUrl(item)} target="_blank" rel="noreferrer">Calendar</a>}<button className="danger" onClick={()=>remove(item)}>Delete</button></span></div>)}</div>}</div></>
}

function CrmView({leads,visibleLeads,loading,search,setSearch,crmFilter,setCrmFilter,updateStage}:{leads:Lead[];visibleLeads:Lead[];loading:boolean;search:string;setSearch:(value:string)=>void;crmFilter:string;setCrmFilter:(value:string)=>void;updateStage:(lead:Lead,status:string)=>void}){
  return <><div className="metrics"><article><span>Total contacts</span><strong>{leads.length}</strong><small>Active CRM records</small></article><article><span>New & pending</span><strong>{leads.filter(x=>['NEW_LEAD','CONSULTATION_REQUESTED','PENDING_APPROVAL'].includes(x.crm_status)).length}</strong><small>Needs qualification</small></article><article><span>Open opportunities</span><strong>{leads.filter(x=>['QUALIFIED','FOLLOW_UP','PROPOSAL_DISCUSSION','INTERESTED_DEAL'].includes(x.crm_status)).length}</strong><small>In active pipeline</small></article><article><span>Closed won</span><strong>{leads.filter(x=>x.crm_status==='CLOSED_WON').length}</strong><small>Converted clients</small></article></div><div className="tableCard"><div className="crmToolbar"><input aria-label="Search CRM" placeholder="Search name, email, phone, location…" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Filter CRM stage" value={crmFilter} onChange={e=>setCrmFilter(e.target.value)}><option value="ALL">All pipeline stages</option>{Object.entries(crmLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></div>{loading?<p className="emptyState">Loading CRM…</p>:visibleLeads.length===0?<p className="emptyState">No leads match this view.</p>:<div className="crmGrid">{visibleLeads.map(lead=><article className="crmCard" key={lead.id}><div className="crmIdentity"><i>{initials(lead.full_name)}</i><div><h3>{lead.full_name}</h3><a href={`mailto:${lead.email}`}>{lead.email}</a><a href={`tel:${lead.mobile}`}>{lead.mobile}</a></div></div><dl><div><dt>Service</dt><dd>{serviceLabels[lead.service_type]||lead.service_type}</dd></div><div><dt>Location</dt><dd>{lead.preferred_location||'Not provided'}</dd></div><div><dt>Qualification</dt><dd>{lead.qualification_status.replaceAll('_',' ')}</dd></div></dl><label>Pipeline stage<select value={lead.crm_status} onChange={e=>void updateStage(lead,e.target.value)}>{Object.entries(crmLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label></article>)}</div>}</div></>
}

function EditorModal({editing,draft,setDraft,newLead,setNewLead,save,create,close}:{editing:Consultation|null;draft:Draft;setDraft:(value:Draft)=>void;newLead:{fullName:string;email:string;mobile:string;location:string;serviceType:string;requestedAt:string};setNewLead:(value:{fullName:string;email:string;mobile:string;location:string;serviceType:string;requestedAt:string})=>void;save:(e:FormEvent)=>void;create:(e:FormEvent)=>void;close:()=>void}){
  return <div className="modalWrap"><div className="modal"><button className="close" aria-label="Close" onClick={close}>×</button>{editing?<form onSubmit={save}><span className="formKicker">EDIT CONSULTATION</span><h2>{editing.leads.full_name}</h2><label>Status<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}>{Object.entries(statusLabels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>Date and time<input required type="datetime-local" value={draft.requestedAt} onChange={e=>setDraft({...draft,requestedAt:e.target.value})}/></label><label>Admin notes<textarea value={draft.adminNotes} onChange={e=>setDraft({...draft,adminNotes:e.target.value})}/></label><div className="formActions"><button className="continue">Save changes</button></div></form>:<form onSubmit={create}><span className="formKicker">NEW CRM RECORD</span><h2>Add a lead</h2><div className="formGrid"><label>Full name<input required value={newLead.fullName} onChange={e=>setNewLead({...newLead,fullName:e.target.value})}/></label><label>Email<input required type="email" value={newLead.email} onChange={e=>setNewLead({...newLead,email:e.target.value})}/></label><label>Mobile<input required value={newLead.mobile} onChange={e=>setNewLead({...newLead,mobile:e.target.value})}/></label><label>Location<input value={newLead.location} onChange={e=>setNewLead({...newLead,location:e.target.value})}/></label><label>Service<select value={newLead.serviceType} onChange={e=>setNewLead({...newLead,serviceType:e.target.value})}>{Object.entries(serviceLabels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>Date and time<input required type="datetime-local" value={newLead.requestedAt} onChange={e=>setNewLead({...newLead,requestedAt:e.target.value})}/></label></div><div className="formActions"><button className="continue">Create lead</button></div></form>}</div></div>
}
